defmodule LiveUi.Widgets do
  @moduledoc """
  Public widget and layout components for composing `live_ui` screens directly.

  These components use the same renderer families as the `UnifiedIUR` path so
  direct composition and interpreted rendering stay aligned.
  """

  use Phoenix.Component

  alias LiveUi.Components.BasicWidgets
  alias LiveUi.Components.DataViz
  alias LiveUi.Components.Extensions
  alias LiveUi.Components.Feedback
  alias LiveUi.Components.Forms
  alias LiveUi.Components.Layouts
  alias LiveUi.Components.Navigation
  alias LiveUi.WidgetRegistry

  attr(:descriptor, :map, required: true)

  def render(assigns) do
    ~H"""
    <WidgetRegistry.render descriptor={@descriptor} />
    """
  end

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:content, :string, default: nil)
  attr(:text, :string, default: nil)
  attr(:signal_bindings, :list, default: [])
  def text(assigns), do: BasicWidgets.text(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:for, :string, default: nil)
  attr(:text, :string, default: nil)
  def label(assigns), do: BasicWidgets.label(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:label, :string, default: nil)
  attr(:text, :string, default: nil)
  attr(:disabled, :boolean, default: false)
  attr(:signal_bindings, :list, default: [])
  def button(assigns), do: BasicWidgets.button(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:value, :string, default: nil)
  attr(:placeholder, :string, default: nil)
  attr(:type, :string, default: nil)
  attr(:input_type, :string, default: nil)
  attr(:disabled, :boolean, default: false)
  attr(:signal_bindings, :list, default: [])
  def text_input(assigns), do: BasicWidgets.text_input(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:spacing, :any, default: nil)
  attr(:gap, :any, default: nil)
  attr(:padding, :any, default: nil)
  attr(:align_items, :string, default: nil)
  attr(:justify_content, :string, default: nil)
  attr(:signal_bindings, :list, default: [])
  slot(:inner_block)
  def vbox(assigns), do: Layouts.vbox(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:spacing, :any, default: nil)
  attr(:gap, :any, default: nil)
  attr(:padding, :any, default: nil)
  attr(:align_items, :string, default: nil)
  attr(:justify_content, :string, default: nil)
  attr(:signal_bindings, :list, default: [])
  slot(:inner_block)
  def hbox(assigns), do: Layouts.hbox(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:gap, :any, default: nil)
  attr(:padding, :any, default: nil)
  attr(:columns, :list, default: nil)
  attr(:rows, :list, default: nil)
  attr(:signal_bindings, :list, default: [])
  slot(:inner_block)
  def grid(assigns), do: Layouts.grid(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:active_index, :any, default: 0)
  attr(:signal_bindings, :list, default: [])
  slot(:panel)
  def stack(assigns), do: Layouts.stack(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:positions, :map, default: %{})
  attr(:signal_bindings, :list, default: [])
  slot(:layer)
  def zbox(assigns), do: Layouts.zbox(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:axis, :string, default: nil)
  attr(:scroll_top, :any, default: 0)
  attr(:scroll_left, :any, default: 0)
  attr(:signal_bindings, :list, default: [])
  slot(:inner_block)
  def viewport(assigns), do: Layouts.viewport(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:gap, :any, default: nil)
  attr(:padding, :any, default: nil)
  attr(:sizes, :list, default: nil)
  attr(:initial_split, :any, default: nil)
  attr(:orientation, :string, default: nil)
  attr(:signal_bindings, :list, default: [])
  slot(:pane)
  def split_pane(assigns), do: Layouts.split_pane(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:label, :string, default: nil)
  attr(:signal_bindings, :list, default: [])
  def command(assigns), do: Navigation.command(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:disabled, :boolean, default: false)
  attr(:label, :string, default: nil)
  attr(:signal_bindings, :list, default: [])
  slot(:inner_block)
  def menu_item(assigns), do: Navigation.menu_item(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:signal_bindings, :list, default: [])
  slot(:inner_block)
  def menu(assigns), do: Navigation.menu(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:signal_bindings, :list, default: [])
  slot(:inner_block)
  def context_menu(assigns), do: Navigation.context_menu(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:disabled, :boolean, default: false)
  attr(:label, :string, default: nil)
  def tab(assigns), do: Navigation.tab(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:active_tab, :string, default: nil)
  attr(:signal_bindings, :list, default: [])

  slot :tab do
    attr(:id, :string, required: true)
    attr(:label, :string)
    attr(:disabled, :boolean)
  end

  def tabs(assigns), do: Navigation.tabs(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:signal_bindings, :list, default: [])
  slot(:inner_block)
  def tree_view(assigns), do: Navigation.tree_view(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:disabled, :boolean, default: false)
  attr(:expanded, :boolean, default: false)
  attr(:label, :string, default: nil)
  attr(:selected, :boolean, default: false)
  attr(:signal_bindings, :list, default: [])
  slot(:inner_block)
  def tree_node(assigns), do: Navigation.tree_node(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:query, :string, default: nil)
  attr(:placeholder, :string, default: nil)
  attr(:active_command_id, :string, default: nil)
  attr(:open, :boolean, default: true)
  attr(:signal_bindings, :list, default: [])
  slot(:inner_block)
  def command_palette(assigns), do: Navigation.command_palette(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:placeholder, :string, default: nil)
  attr(:signal_bindings, :list, default: [])
  slot(:inner_block)
  def pick_list(assigns), do: Forms.pick_list(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:label, :string, default: nil)
  attr(:selected, :boolean, default: false)
  attr(:value, :string, default: nil)
  def pick_list_option(assigns), do: Forms.pick_list_option(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:default, :any, default: nil)
  attr(:disabled, :boolean, default: false)
  attr(:field_type, :any, default: nil)
  attr(:label, :string, default: nil)
  attr(:name, :string, default: nil)
  attr(:options, :list, default: [])
  attr(:placeholder, :string, default: nil)
  attr(:type, :any, default: nil)
  def form_field(assigns), do: Forms.form_field(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:submit_label, :string, default: nil)
  attr(:signal_bindings, :list, default: [])
  slot(:inner_block)
  def form_builder(assigns), do: Forms.form_builder(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:header, :string, default: nil)
  attr(:key, :string, default: nil)
  def column(assigns), do: Forms.column(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:columns, :list, default: [])
  attr(:data, :list, default: [])
  attr(:selected_row_id, :any, default: nil)
  attr(:selected_row_index, :any, default: nil)
  attr(:sort_column, :any, default: nil)
  attr(:sort_direction, :any, default: nil)
  attr(:signal_bindings, :list, default: [])
  def table(assigns), do: Forms.table(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:label, :string, default: nil)
  attr(:signal_bindings, :list, default: [])
  def dialog_button(assigns), do: Feedback.dialog_button(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:title, :string, default: nil)
  attr(:modal, :boolean, default: true)
  slot(:inner_block)
  slot(:action)
  def dialog(assigns), do: Feedback.dialog(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:title, :string, default: nil)
  attr(:message, :string, default: nil)
  attr(:signal_bindings, :list, default: [])
  def alert_dialog(assigns), do: Feedback.alert_dialog(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:message, :string, default: nil)
  def toast(assigns), do: Feedback.toast(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:label, :string, default: nil)
  attr(:value, :any, default: nil)
  attr(:max, :any, default: nil)
  attr(:min, :any, default: nil)
  def gauge(assigns), do: DataViz.gauge(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:data, :list, default: [])
  def sparkline(assigns), do: DataViz.sparkline(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:title, :string, default: nil)
  attr(:data, :list, default: [])
  def bar_chart(assigns), do: DataViz.bar_chart(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:title, :string, default: nil)
  attr(:data, :list, default: [])
  def line_chart(assigns), do: DataViz.line_chart(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:title, :string, default: nil)
  attr(:series, :list, default: [])
  def chart(assigns), do: DataViz.chart(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:title, :string, default: nil)
  attr(:draw, :list, default: nil)
  attr(:operations, :list, default: nil)
  def canvas(assigns), do: DataViz.canvas(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:filter, :string, default: nil)
  attr(:lines, :list, default: [])
  attr(:source, :string, default: nil)
  attr(:signal_bindings, :list, default: [])
  def log_viewer(assigns), do: Extensions.log_viewer(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:title, :string, default: nil)
  attr(:items, :list, default: nil)
  attr(:lines, :list, default: nil)
  attr(:buffer_size, :any, default: nil)
  attr(:signal_bindings, :list, default: [])
  def stream_widget(assigns), do: Extensions.stream_widget(assigns)

  attr(:id, :string, default: nil)
  attr(:style, :map, default: %{})
  attr(:class, :any, default: nil)
  attr(:visible, :boolean, default: true)
  attr(:node, :string, default: nil)
  attr(:processes, :list, default: [])
  attr(:selected_pid, :string, default: nil)
  attr(:signal_bindings, :list, default: [])
  def process_monitor(assigns), do: Extensions.process_monitor(assigns)
end
